# Build stage
FROM node:18-alpine AS builder
WORKDIR /react_front
COPY package*.json ./
RUN npm ci 

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine AS production
COPY --from=builder /react_front/dist /usr/share/nginx/html
COPY nginx.docker.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]